---
- name: RH1 Demo | Build RHEL Image Mode container
  hosts: build_host
  tasks:
    - name: RH1 Demo | Set working directory
      ansible.builtin.set_fact:
        workdir: "{{ lookup('env', 'HOME') }}/rhel-image-mode"

    - name: RH1 Demo | Cleanup local working directory
      ansible.builtin.file:
        path: "{{ workdir }}"
        state: absent
