---
- name: RH1 Demo | Build RHEL Image Mode container
  hosts: build_host
  tasks:
    - name: RH1 Demo | Set working directory
      ansible.builtin.set_fact:
        workdir: "{{ lookup('env', 'HOME') }}/rhel-image-mode"
          
    - name: OCP | Login to OCP cluster
      block:
        - name: OCP | Login into OpenShift Container Platform cluster
          redhat.openshift.openshift_auth:
            host: "{{ ocp_api }}"
            username: "{{ ocp_username }}"
            password: "{{ ocp_password }}"
            validate_certs: false
          register: _openshift_auth_results

        - name: Retrieving OCP api_key
          ansible.builtin.set_fact:
            ocp_api_key: "{{ _openshift_auth_results.openshift_auth.api_key }}"

    - name: RH1 Demo | Destroy the VirtualMachine
      redhat.openshift_virtualization.kubevirt_vm:
        host: "{{ ocp_api }}"
        api_key: "{{ ocp_api_key }}"
        validate_certs: false
        state: absent
        name: rhel-image-mode-vm
        namespace: rh1-demo

    - name: RH1 Demo | Ensure OCP-V DataImport is absent
      redhat.openshift.k8s:
        host: "{{ ocp_api }}"
        api_key: "{{ ocp_api_key }}"
        validate_certs: false             
        state: absent
        resource_definition:
          apiVersion: cdi.kubevirt.io/v1beta1
          kind: DataImportCron
          metadata:
            name: rhel-image-mode
            namespace: openshift-virtualization-os-images

    - name: RH1 Demo | Ensure OCP-V DataSource is absent
      redhat.openshift.k8s:
        host: "{{ ocp_api }}"
        api_key: "{{ ocp_api_key }}"
        validate_certs: false             
        state: absent
        resource_definition:
          apiVersion: cdi.kubevirt.io/v1beta1
          kind: DataSource
          metadata:
            name: rhel-image-mode
            namespace: openshift-virtualization-os-images


    - name: RH1 Demo | Cleanup local working directory
      ansible.builtin.file:
        path: "{{ workdir }}"
        state: absent
