---
- name: RH1 Demo | Build RHEL Image Mode container
  hosts: build_host
  vars_files:
    - vars.yml
  tasks:
    - name: RH1 Demo | Set working directory
      ansible.builtin.set_fact:
        workdir: "/home/{{ ansible_user }}/rhel-image-mode"

    - name: RH1 Demo | Clone app repo
      ansible.builtin.git:
        repo: "{{ image_mode_application_repo }}"
        dest: "{{ workdir }}"

    - name: RH1 Demo | Login to registry
      containers.podman.podman_login:
        registry: "{{ rhel_image_mode_registry_url }}"
        username: "{{ rhel_image_mode_registry_username }}"
        password: "{{ rhel_image_mode_registry_password }}"

    - name: RH1 Demo | Build RHEL Image
      containers.podman.podman_image:
        name: "{{ rhel_image_mode_registry_url }}/{{ rhel_image_mode_registry_username }}/rhel-image-mode-demo:vm"
        build_args:
          force_rm: true
        path: "{{ workdir }}"

    - name: RH1 Demo | Run Image Vulnerability Scan
      ansible.builtin.shell:
        cmd: "trivy image --db-repository public.ecr.aws/aquasecurity/trivy-db:2 --scanners vuln {{ rhel_image_mode_registry_url }}/{{ rhel_image_mode_registry_username }}/rhel-image-mode-demo:vm"
      register: image_scan

    - name: RH1 Demo | Print scan results
      ansible.builtin.debug:
        msg:
          "{{ image_scan.stdout_lines }}"

    - name: RH1 Demo | Push RHEL Image
      containers.podman.podman_image:
        name: "{{ rhel_image_mode_registry_url }}/{{ rhel_image_mode_registry_username }}/rhel-image-mode-demo:vm"
        build_args:
          force_rm: true
        path: "{{ workdir }}"
        push: true
