---
- name: RH1 Demo | Build RHEL Image Mode container
  hosts: build_host
  tasks:
    - name: RH1 Demo | Set working directory
      ansible.builtin.set_fact:
        workdir: "{{ lookup('env','HOME') }}/rhel-image-mode"

    - name: RH1 Demo | Ensure packages are up to date
      become: true
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: RH1 Demo | Ensure Podman is present
      become: true
      ansible.builtin.dnf:
        name: container-tools
        state: present

    - name: RH1 Demo | Create local working directory
      ansible.builtin.file:
        path: "{{ workdir }}/output"
        state: directory
        mode: "0775"
    
    - name: RH1 Demo | Copy containerfile
      ansible.builtin.copy:
        src: ./files/
        dest: "{{ workdir }}/"
        mode: "0775"

    - name: RH1 Demo | Login to registry
      containers.podman.podman_login:
        registry: "{{ rhel_image_mode_registry_url }}"
        username: "{{ rhel_image_mode_registry_username }}"
        password: "{{ rhel_image_mode_registry_password }}"

    - name: RH1 Demo | Build and push RHEL Image
      containers.podman.podman_image:
        name: "{{ rhel_image_mode_registry_url }}/{{ rhel_image_mode_registry_username }}/rhel-image-mode-demo:vm"
        build_args:
          force_rm: true
          container_file: "{{ workdir }}/Containerfile.build"
        path: ./files
        push: true

    - name: RH1 Demo | Generate output folder for resulting image
      ansible.builtin.file:
        path: "{{ workdir }}/output"

    - name: RH1 Demo | Generate QCOW Image with bootc-image-builder
      become: true
      containers.podman.podman_container:
        name: bootc-image-builder
        image: registry.redhat.io/rhel9/bootc-image-builder:latest
        privileged: true
        remove: true
      
        pull: newer
        security_opt:
          - label=type:unconfined_t
        state: started
        ports:
          - "8080:80"
        volumes:
          - "/var/lib/containers/storage:/var/lib/containers/storage"
          - "{{ workdir }}/output:/output"
        command: "--type qcow2 {{ rhel_image_mode_registry_url }}/{{ rhel_image_mode_registry_username }}/rhel-image-mode-demo"

    - name: RH1 Demo | Wait for image to be generated. It can take a while.
      ansible.builtin.wait_for:
        path: "{{ workdir }}/output/qcow2/disk.qcow2"
        state: present

    - name: RH1 Demo | Generate and push container image for OCP Virt
      containers.podman.podman_image:
        name: "{{ rhel_image_mode_registry_url }}/{{ rhel_image_mode_registry_username }}/rhel-image-mode-demo:ocpvirt"
        path: ./files
        build_args:
          force_rm: true
          container_file: "{{ workdir }}/Containerfile.ocpvirt"        
        push: true
