---
- name: RH1 Demo | Build RHEL Image Mode container
  hosts: build_host
  tasks:
    - name: RH1 Demo | Set working directory
      ansible.builtin.set_fact:
        workdir: "{{ lookup('env', 'HOME') }}/rhel-image-mode"

    - name: RH1 Demo | Set-up trivy scanning
      become: true
      block:
        - name: RH1 Demo | Add trivy repo
          ansible.builtin.yum_repository:
            name: Trivy repository
            baseurl: https://aquasecurity.github.io/trivy-repo/rpm/releases/$releasever/$basearch/
            gpgcheck: false
            enabled: true
            description: Trivy Repo

        - name: RH1 Demo | Install trivy
          ansible.builtin.dnf:
            name: trivy
            state: present

    - name: RH1 Demo | Create local working directory
      ansible.builtin.file:
        path: "{{ workdir }}/output"
        state: directory
        mode: "0775"

    - name: RH1 Demo | Copy containerfile
      ansible.builtin.copy:
        src: ./files/
        dest: "{{ workdir }}/"
        mode: "0775"

    - name: RH1 Demo | Login to registry
      containers.podman.podman_login:
        registry: "{{ rhel_image_mode_registry_url }}"
        username: "{{ rhel_image_mode_registry_username }}"
        password: "{{ rhel_image_mode_registry_password }}"

    - name: RH1 Demo | Build and push RHEL Image
      containers.podman.podman_image:
        name: "{{ rhel_image_mode_registry_url }}/{{ rhel_image_mode_registry_username }}/rhel-image-mode-demo:vm"
        build_args:
          force_rm: true
        path: "{{ workdir }}"

    - name: RH1 Demo | Run Image Vulnerability Scan
      ansible.builtin.shell:
        command: "trivy image --db-repository public.ecr.aws/aquasecurity/trivy-db:2 --scanners vuln {{ rhel_image_mode_registry_url }}/{{ rhel_image_mode_registry_username }}/rhel-image-mode-demo:vm"
      register: image_scan

    - name: Debug
      ansible.builtin.debug:
        var: image_scan