---
- name: RH1 Demo | Build RHEL Image Mode container
  hosts: build_host
  tasks:
    - name: RH1 Demo | Set working directory
      ansible.builtin.set_fact:
        workdir: "{{ lookup('env', 'HOME') }}/rhel-image-mode"

    - name: RH1 Demo | Copy containerfile
      ansible.builtin.copy:
        src: ./files/
        dest: "{{ workdir }}/"
        mode: "0775"

    - name: RH1 Demo | Login to registry
      containers.podman.podman_login:
        registry: "{{ rhel_image_mode_registry_url }}"
        username: "{{ rhel_image_mode_registry_username }}"
        password: "{{ rhel_image_mode_registry_password }}"

    - name: RH1 Demo | Build and push RHEL Image
      containers.podman.podman_image:
        name: "{{ rhel_image_mode_registry_url }}/{{ rhel_image_mode_registry_username }}/rhel-image-mode-demo:vm"
        build_args:
          force_rm: true
        path: "{{ workdir }}"

    - name: RH1 Demo | Run Image Vulnerability Scan
      ansible.builtin.shell:
        cmd: "trivy image --db-repository public.ecr.aws/aquasecurity/trivy-db:2 --scanners vuln {{ rhel_image_mode_registry_url }}/{{ rhel_image_mode_registry_username }}/rhel-image-mode-demo:vm"
      register: testing

    # - name: RH1 Demo | Fetch report
    #   ansible.builtin.slurp:
    #     src: "report"
    #   register: image_scan

    - name: Debug testing
      ansible.builtin.debug:
        msg:
          "{{ testing.stdout_lines }}"

    # - name: Debug
    #   ansible.builtin.debug:
    #     msg: "{{ image_scan.content | b64decode }}"