---
- name: RH1 Demo | Webhook | Listen for events on a webhook
  hosts: localhost

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5010
  rules:
    - name: RH1 Demo | Webhook | React to new tag creation
      condition: event.meta.headers["X-Github-Event"] == 'create'
      actions:
        - debug:
        - run_job_template:
            name: "[RH1 Demo] Build Image Mode update"
            organization: Default
