---
- name: RH1 Demo | Build RHEL Image Mode SOE Container
  hosts: build_host
  vars_files:
    - vars.yml
  tasks:
    - name: RH1 Demo | Set working directory
      ansible.builtin.set_fact:
        workdir: "/home/{{ ansible_user }}/rhel-image-mode"

    - name: RH1 Demo | Clone SOE repo
      ansible.builtin.git:
        repo: "{{ image_mode_soe_repo }}"
        dest: "{{ workdir }}/soe-repo"

    - name: RH1 Demo | Login to registry
      containers.podman.podman_login:
        registry: "{{ rhel_image_mode_registry_url }}"
        username: "{{ rhel_image_mode_registry_username }}"
        password: "{{ rhel_image_mode_registry_password }}"

    - name: RH1 Demo | Build and push RHEL Image
      containers.podman.podman_image:
        name: "{{ rhel_image_mode_registry_url }}/{{ rhel_image_mode_registry_username }}/rhel-image-mode-demo:soe"
        build_args:
          force_rm: true
          file: Containerfile.soe
        path: "{{ workdir }}/soe-repo"
        push: true

    # - name: RH1 Demo | Cleanup local working directory
    #   ansible.builtin.file:
    #     path: "{{ workdir }}/soe-repo"
    #     state: absent
