---
- name: RH1 Demo | Build RHEL Image Mode container
  hosts: build_host
  tasks:
    - name: RH1 Demo | Set working directory
      ansible.builtin.set_fact:
        workdir: "/home/{{ ansible_user }}/rhel-image-mode"

    - name: RH1 Demo | Ensure packages are up to date
      become: true
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: RH1 Demo | Ensure Podman is present
      become: true
      ansible.builtin.dnf:
        name: container-tools
        state: present

    - name: Enable Linger for user
      ansible.builtin.command:
        argv:
          - /usr/bin/loginctl
          - enable-linger
          - "{{ ansible_user }}"
        creates: "/var/lib/systemd/linger/{{ ansible_user }}"

    - name: RH1 Demo | Enable Podman socket for image scanning
      ansible.builtin.systemd_service:
        name: podman.socket
        state: started
        enabled: true
        scope: user

    - name: RH1 Demo | Set-up trivy scanning
      become: true
      block:
        - name: RH1 Demo | Add trivy repo
          ansible.builtin.yum_repository:
            name: trivy_repository
            baseurl: https://aquasecurity.github.io/trivy-repo/rpm/releases/$releasever/$basearch/
            gpgcheck: false
            enabled: true
            description: Trivy Repo

        - name: RH1 Demo | Install trivy
          ansible.builtin.dnf:
            name: trivy
            state: present

    - name: RH1 Demo | Create local working directory
      ansible.builtin.file:
        path: "{{ workdir }}/output"
        state: directory
        mode: "0775"

    - name: RH1 Demo | Retrieve CA Cert for Gitea
      community.crypto.get_certificate:
        host: rhel9-server.rh-lab.labs
        port: "{{ gitea_server_port | default('3000', true) }}"
      register: _gitea_ca
      delegate_to: localhost

    - name: RH1 Demo | Store CA Cert in trust
      become: true
      ansible.builtin.copy:
        content: "{{ _gitea_ca.cert }}"
        dest: /etc/pki/ca-trust/source/anchors/gitea-ca.pem
        mode: "0755"

    - name: RH1 Demo | Trust CA Cert for Gitea
      become: true
      ansible.builtin.shell:
        cmd: update-ca-trust

- name: RH1 Demo | Build RHEL Image Mode container
  hosts: webserver
  tasks:
    - name: RH1 Demo | Setup httpd
      become: true
      block:
        - name: RH1 Demo | Ensure httpd is present
          ansible.builtin.dnf:
            name: httpd
            state: present

        - name: RH1 Demo | Create folder for bootc bits
          ansible.builtin.file:
            path: /var/www/html/bootc/
            state: directory
            mode: "0755"

        - name: RH1 Demo | Ensure httpd unit is enabled
          ansible.builtin.service:
            name: httpd
            enabled: true
            state: restarted
