---
- name: RH1 Demo | Build RHEL Image Mode container
  hosts: build_host
  tasks:
    - name: RH1 Demo | Set working directory
      ansible.builtin.set_fact:
        workdir: "/home/{{ ansible_user }}/rhel-image-mode"

    - name: RH1 Demo | Push RHEL Image
      containers.podman.podman_image:
        name: "{{ custom_registry_url }}/{{ custom_registry_username }}/rhel-image-mode-demo"
        path: "{{ workdir }}/{{ build_folder }}"
        push: true
        pull: false
        tag: "{{ item }}"
      loop:
          - "{{ image_tag }}"
          - "{{ image_tag }}-{{ git_tag }}"

    - name: RH1 Demo | Cleanup local working directory
      ansible.builtin.file:
        path: "{{ workdir }}"
        state: absent
