---
- name: RH1 Demo | Build RHEL Image Mode container
  hosts: build_host
  tasks:
    - name: RH1 Demo | Set working directory
      ansible.builtin.set_fact:
        workdir: "/home/{{ ansible_user }}/rhel-image-mode"

    - name: RH1 Demo | Clone repo
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ workdir }}/{{ build_folder }}"

    - name: RH1 Demo | Login to registry
      no_log: true
      containers.podman.podman_login:
        registry: "{{ item.registry }}"
        username: "{{ item.username }}"
        password: "{{ item.password }}"
      loop:
        - registry: "{{ rhel_image_mode_registry_url }}"
          username: "{{ rhel_image_mode_registry_username }}"
          password: "{{ rhel_image_mode_registry_password }}"
        - registry: "{{ redhat_registry_url }}"
          username: "{{ redhat_registry_username }}"
          password: "{{ redhat_registry_password }}"

    - name: RH1 Demo | Build RHEL Image
      containers.podman.podman_image:
        name: "{{ rhel_image_mode_registry_url }}/{{ rhel_image_mode_registry_username }}/rhel-image-mode-demo:{{ image_tag }}"
        build_args:
          force_rm: true
          extra_args: "--build-arg REGISTRY_URL={{ rhel_image_mode_registry_url }} --build-arg REGISTRY_USER={{ rhel_image_mode_registry_username }}"
        path: "{{ workdir }}/{{ build_folder }}"
        pull: false

    - name: RH1 Demo | Tag Image
      containers.podman.podman_tag:
        image: "{{ rhel_image_mode_registry_url }}/{{ rhel_image_mode_registry_username }}/rhel-image-mode-demo:{{ image_tag }}"
        target_names:
          - "{{ rhel_image_mode_registry_url }}/{{ rhel_image_mode_registry_username }}/rhel-image-mode-demo:{{ image_tag }}-{{ git_tag }}"

    - name: RH1 Demo | Run Image Vulnerability Scan
      ansible.builtin.shell:
        cmd: "trivy image --java-db-repository public.ecr.aws/aquasecurity/trivy-java-db --db-repository public.ecr.aws/aquasecurity/trivy-db --scanners vuln {{ rhel_image_mode_registry_url }}/{{ rhel_image_mode_registry_username }}/rhel-image-mode-demo:{{ image_tag }}"
      register: image_scan

    - name: RH1 Demo | Print scan results
      ansible.builtin.debug:
        msg:
          "{{ image_scan.stdout_lines }}"
