---
- name: RH1 Demo | Build RHEL Image Mode container
  hosts: build_host
  tasks:
    - name: RH1 Demo | Set working directory
      ansible.builtin.set_fact:
        workdir: "/home/{{ ansible_user }}/rhel-image-mode"

    - name: RH1 Demo | Ensure packages are up to date
      become: true
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: RH1 Demo | Ensure Podman is present
      become: true
      ansible.builtin.dnf:
        name: container-tools
        state: present

    - name: RH1 Demo | Set-up trivy scanning
      become: true
      block:
        - name: RH1 Demo | Add trivy repo
          ansible.builtin.yum_repository:
            name: Trivy repository
            baseurl: https://aquasecurity.github.io/trivy-repo/rpm/releases/$releasever/$basearch/
            gpgcheck: false
            enabled: true
            description: Trivy Repo

        - name: RH1 Demo | Install trivy
          ansible.builtin.dnf:
            name: trivy
            state: present

    - name: RH1 Demo | Create local working directory
      ansible.builtin.file:
        path: "{{ workdir }}/output"
        state: directory
        mode: "0775"

- name: RH1 Demo | Build RHEL Image Mode container
  hosts: webserver
  tasks:
    - name: RH1 Demo | Setup httpd
      become: true
      block:
        - name: RH1 Demo | Ensure httpd is present
          ansible.builtin.dnf:
            name: httpd
            state: present

        - name: RH1 Demo | Create folder for bootc bits
          ansible.builtin.file:
            path: /var/www/html/bootc/
            state: directory
            mode: "0755"

        - name: RH1 Demo | Ensure httpd unit is enabled
          ansible.builtin.service:
            name: httpd
            enabled: true
            state: restarted
