---
- name: RH1 Demo | Build RHEL Image Mode container
  hosts: build_host
  vars_files:
    - vars.yml
  tasks:
    - name: RH1 Demo | Set working directory
      ansible.builtin.set_fact:
        workdir: "/home/{{ ansible_user }}/rhel-image-mode"

    - name: RH1 Demo | Push RHEL Image
      containers.podman.podman_image:
        name: "{{ rhel_image_mode_registry_url }}/{{ rhel_image_mode_registry_username }}/rhel-image-mode-demo:vm"
        build_args:
          force_rm: true
        path: "{{ workdir }}/image-repo"
        push: true

    - name: RH1 Demo | Cleanup local working directory
      ansible.builtin.file:
        path: "{{ workdir }}"
        state: absent
